#!/bin/sh -e

cmd=$1
shift
case "$cmd" in
  build-exclude-list|dist-exclude-list|prepare-dist)
    ;;
  bootstrap)
    mkdir -p m4
    autoreconf --install --force
    ;;
  configure)
    ./configure $@
    ;;
  make)
    make $@
    ;;
  *)
    echo "Unknown command: $cmd"
    exit 1
    ;;
esac
exit 0

# vim: ts=2 sw=2 expandtab
